# Generated by Django 4.2.10 on 2025-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="black_date",
        ),
        migrations.AddField(
            model_name="user",
            name="block_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="block date"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="attempts count"
            ),
        ),
    ]
