# Generated by Django 4.2.10 on 2025-04-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("in processing", "in processing"),
                            ("response given", "response given"),
                        ],
                        default="received",
                        help_text="Processing status",
                        max_length=20,
                        verbose_name="processing status",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Feedback content",
                        max_length=10240,
                        verbose_name="text",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date of feedback creation",
                        verbose_name="created",
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback",
                "verbose_name_plural": "feedbacks",
            },
        ),
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="Feedback author",
                        max_length=100,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Feedback author's email",
                        max_length=200,
                        verbose_name="email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time of status change",
                        verbose_name="time",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        db_column="from",
                        help_text="From which status",
                        max_length=20,
                        verbose_name="from status",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        db_column="to",
                        help_text="To which status",
                        max_length=20,
                        verbose_name="to status",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        help_text="Feedback for which the status was changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="feedback.feedback",
                        verbose_name="feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "status change log",
                "verbose_name_plural": "status change logs",
            },
        ),
    ]
