# Generated by Django 4.2.10 on 2025-04-14 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                db_column="User_key",
                help_text="User who changed the status",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="status_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="personaldata",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the feedback",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="personal_data",
            field=models.OneToOneField(
                default=None,
                help_text="Author's personal data",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedback",
                to="feedback.personaldata",
                verbose_name="personal data",
            ),
        ),
    ]
