# Generated by Django 4.2.10 on 2025-04-27 10:18

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Note image/profile avatar",
                        null=True,
                        upload_to=apps.core.models.BaseImageModel.upload_to_path,
                        verbose_name="image/avatar",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Write title news",
                        max_length=250,
                        verbose_name="Title news",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Write description news",
                        max_length=500,
                        verbose_name="Description news",
                    ),
                ),
            ],
            options={
                "verbose_name": "news",
                "verbose_name_plural": "news",
            },
        ),
    ]
