# Generated by Django 4.2.10 on 2025-05-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date create news",
                null=True,
                verbose_name="Create at",
            ),
        ),
    ]
