# Generated by Django 4.2.10 on 2025-05-22 06:14

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_create_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="create_at",
        ),
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.AddField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time created",
                null=True,
                verbose_name="created at",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date last update",
                null=True,
                verbose_name="update at",
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Note image/profile avatar",
                        null=True,
                        upload_to=apps.core.models.BaseImageModel.upload_to_path,
                        verbose_name="image/avatar",
                    ),
                ),
                (
                    "news",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="news.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "main image news",
                "verbose_name_plural": "main images news",
            },
        ),
    ]
