# Generated by Django 4.2.10 on 2025-04-27 21:07

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True,
                        help_text="title chat",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time created chat",
                        verbose_name="created at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="user chat/none",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="user message/none",
                        verbose_name="text",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="video in the first message form AI",
                        null=True,
                        upload_to="chat/videos",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time created message",
                        verbose_name="created at",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="messege in chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Note image/profile avatar",
                        null=True,
                        upload_to=apps.core.models.BaseImageModel.upload_to_path,
                        verbose_name="image/avatar",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="img in msg",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
