# Generated by Django 4.2.10 on 2025-05-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_ai",
            field=models.BooleanField(
                default=False,
                help_text="msg from ai/user",
                verbose_name="is ai",
            ),
        ),
    ]
