# Generated by Django 4.2.10 on 2025-05-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_is_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date last update",
                null=True,
                verbose_name="update at",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date last update",
                null=True,
                verbose_name="update at",
            ),
        ),
    ]
